# Generated by Django 2.0.1 on 2018-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='pem',
            field=models.TextField(blank=True, help_text='Super long private key, usually begins with: -----BEGIN PRIVATE KEY-----. This is an unsecure way to store very important keys', verbose_name='PEM'),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='type',
            field=models.CharField(blank=True, help_text='Type, level or purpose of key', max_length=191, verbose_name='Type'),
        ),
    ]
