# Generated by Django 2.2.1 on 2019-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20180410_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
